name: chickies_ui
description: Dart package which defines chikies ui components.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  # flutter: ^3.19.2
dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true