name: SmartMicro.Mobile
description:
  A Flutter project showcasing supported Material 3 components, typography, color system and elevation.
  Supports different light/dark mode, color seed, and comparison to Material 2.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.3.0
  flutter: ^3.19.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.8
  # web_startup_analyzer:
  #   path: ../web/_packages/web_startup_analyzer


  chickies_ui:
    path: packages/chickies_ui
    
  flutter_blue_plus: ^1.31.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - utils/